"""Street mapping data for the Petrus broker spreadsheet adapter.

Contains STREET_CANONICAL (raw variations → canonical key) and
STREET_INFO (canonical key → logradouro type + official name).

This data was extracted from the broker's ETL pipeline configuration
and covers ~300 streets in the Alphaville/Barueri region of São Paulo.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# STREET_CANONICAL
# ---------------------------------------------------------------------------
# Maps raw street name variations (lowercase, stripped) to a canonical key.

STREET_CANONICAL: dict[str, str] = {
    # -- Alphaville Industrial --
    "africa": "africa",
    "áfrica": "africa",
    "aldeinha": "aldeinha",
    "aldeinha 220": "aldeinha",
    "amazonas": "amazonas",
    "amazonas a": "amazonas",
    "amazonas b": "amazonas",
    "amazonas faze": "amazonas_fazendinha",
    "amazonas fazen": "amazonas_fazendinha",
    "amazonas fazendinha": "amazonas_fazendinha",
    "america": "america",
    "américa": "america",
    "america/asia": "america",
    "araguacema": "araguacema",
    "araguacema euro": "araguacema",
    "araguaia": "araguaia",
    "araguaia       910": "araguaia",
    "arapoema": "arapoema",
    "arapoema/juari": "arapoema",
    "aruanã": "aruanã",
    "aruana": "aruanã",
    "aruanã        671": "aruanã",
    "aruanã       700": "aruanã",
    "aruanã       813": "aruanã",
    "aruanã       940": "aruanã",
    "aruanã wlc": "aruanã",
    "asia": "asia",
    "ásia": "asia",
    "ásia ": "asia",
    "asia térreo res": "asia",
    "asia terreo res": "asia",
    "asia térreo": "asia",
    "asia terreo": "asia",
    "asia 1º andar": "asia",
    "asia 2º andar": "asia",
    "asia 3º andar": "asia",
    "bahia": "bahia",
    "caiapós": "caiapos",
    "caiapos": "caiapos",
    "caiapós 790": "caiapos",
    "caiapos 790": "caiapos",
    "caiapós/ceci": "caiapos",
    "caiapos/ceci": "caiapos",
    "ceará": "ceara",
    "ceara": "ceara",
    "ceci": "ceci",
    "ceci q6": "ceci",
    "ceci technology": "ceci",
    "ceci technol": "ceci",
    "ceci technolg10": "ceci",
    "cecitechnology": "ceci",
    "cecitechnol": "ceci",
    "cecitechnolg10": "ceci",
    "dib sauaia": "dib_sauaia",
    "dib sauaia loja": "dib_sauaia",
    "europa": "europa",
    "europa 945": "europa",
    "estr mun b. vista": "estr_mun_boa_vista",
    "estr mun b.vista": "estr_mun_boa_vista",
    "estr mun boa vista": "estr_mun_boa_vista",
    "grajaú": "grajau",
    "grajau": "grajau",
    "hon alv pente": "hon_alv_pente",
    "honorio a.pent": "hon_alv_pente",
    "honório a.pent": "hon_alv_pente",
    "ibateguara": "ibateguara",
    "inajá": "inaja",
    "inaja": "inaja",
    "javari": "javari",
    "joão f camargo": "joao_f_camargo",
    "joao f camargo": "joao_f_camargo",
    "josé pereira sb": "jose_pereira_sb",
    "jose pereira sb": "jose_pereira_sb",
    "juari": "juari",
    "juruá": "jurua",
    "jurua": "jurua",
    "juruá 314": "jurua",
    "jurua 314": "jurua",
    "juruá 370": "jurua",
    "jurua 370": "jurua",
    "juruá 762": "jurua",
    "jurua 762": "jurua",
    "jussara": "jussara",
    "jussara/piram": "jussara",
    "madeira": "madeira",
    "marcos ulhoa": "marcos_ulhoa",
    "marco ulhoa": "marcos_ulhoa",
    "marg proj": "marg_projetada",
    "marg projetada": "marg_projetada",
    "modular": "modular_i",
    "modular i": "modular_i",
    "modular ii": "modular_ii",
    "oceania": "oceania",
    "piracema": "piracema",
    "piraiba": "piraiba",
    "piraíba": "piraiba",
    "piraiba/aruanã": "piraiba",
    "piraíba/aruanã": "piraiba",
    "pirambóia": "piramboia",
    "piramboia": "piramboia",
    "pucuruí": "pucurui",
    "pucurui": "pucurui",
    "rio negro": "rio_negro",
    "rio preto": "rio_preto",
    "rio preto a": "rio_preto",
    "são paulo": "sao_paulo",
    "sao paulo": "sao_paulo",
    "são paulo esqu": "sao_paulo",
    "sao paulo esqu": "sao_paulo",
    "surubiju": "surubiju",
    "tambaqui": "tambaqui",
    "tamboré": "tambore",
    "tambore": "tambore",
    "tamboré 341": "tambore",
    "tambore 341": "tambore",
    "tamboré mult 1": "tambore",
    "tambore mult 1": "tambore",
    "tocantins": "tocantins",
    "tocantins g": "tocantins",
    "tocantins mult3": "tocantins",
    "trevo de alpha": "trevo_alphaville",
    "trevo de alphaville": "trevo_alphaville",
    "trix": "trix",
    "tucunaré": "tucunare",
    "tucunare": "tucunare",
    "victorino": "victorino_calegare",
    "victorino calegare": "victorino_calegare",
    "vitori calegari": "victorino_calegare",
    "victorino calegari": "victorino_calegare",
    "xingu": "xingu",
    "yojiro takaoka": "yojiro_takaoka",

    # -- Barueri --
    "abaetetuba": "abaetetuba",
    "abatetuba": "abaetetuba",
    "abelardo luz": "abelardo_luz",
    "aeroporto": "aeroporto",
    "alfredo bicasa": "alfredo_bicasa",
    "amor perfeito": "amor_perfeito",
    "antilhas": "antilhas",
    "anton saviano": "anton_saviano",
    "aquario": "aquario",
    "aquário": "aquario",
    "arara": "araras",
    "araras": "araras",
    "atenas": "atenas",
    "av marco": "av_marco",
    "barueri mirim": "barueri_mirim",
    "benedito dias": "benedito_turibio",
    "beneditoturibio": "benedito_turibio",
    "bened a turibio": "benedito_turibio",
    "benedito turibio": "benedito_turibio",
    "betha trindade": "betha_trindade",
    "betha  trindade": "betha_trindade",
    "bethaville": "bethaville",
    "loja bethaville": "bethaville",
    "predio bethavi": "bethaville",
    "bica": "bica",
    "boa vista": "boa_vista",
    "brasil": "brasil",
    "brasilandia": "brasilandia",
    "brasilândia": "brasilandia",
    "brooklin": "brooklin",
    "c.e.itaqui": "ce_itaqui",
    "c.e. itaqui": "ce_itaqui",
    "ce itaqui": "ce_itaqui",
    "c.l. itapevi": "cl_itapevi",
    "c.l.itapevi": "cl_itapevi",
    "cl itapevi": "cl_itapevi",
    "cachoeira": "cachoeira",
    "calil mohamed": "calil_mohamed",
    "campo grande": "campo_grande",
    "capitais": "capitais",
    "cast branco": "castelo_branco",
    "chaves": "chaves",
    "cicero b morais": "cicero_b_morais",
    "cícero b morais": "cicero_b_morais",
    "constantinopla": "constantinopla",
    "dário almonacid": "dario_almonacid",
    "dario almonacid": "dario_almonacid",
    "emilio b silva": "emilio_b_silva",
    "emílio b silva": "emilio_b_silva",
    "esp. santo": "espirito_santo",
    "espirito santo": "espirito_santo",
    "espírito santo": "espirito_santo",
    "estados": "estados",
    "estr alpes": "estr_alpes_beriolo",
    "estr alpes bério": "estr_alpes_beriolo",
    "estr alpes berio": "estr_alpes_beriolo",
    "estr dos alpes": "estr_alpes_beriolo",
    "estr. altos": "estr_alpes_beriolo",
    "estr da balsa": "estr_da_balsa",
    "estr. balsa": "estr_da_balsa",
    "estr da cachoei": "estr_da_cachoeira",
    "estr da cachoeira": "estr_da_cachoeira",
    "estr do ingaí": "estr_do_ingai",
    "estr do ingai": "estr_do_ingai",
    "estr. do ingaí": "estr_do_ingai",
    "estr. do ingai": "estr_do_ingai",
    "estr do itaqui": "estr_do_itaqui",
    "estr do zilo": "estr_do_zilo",
    "estr emilio scaff": "estr_emilio_scaff",
    "estr emílio scaff": "estr_emilio_scaff",
    "estr nações": "estr_nacoes",
    "estr nacoes": "estr_nacoes",
    "estr v. cotia": "estr_velha_cotia",
    "estr v.cotia": "estr_velha_cotia",
    "estr velha cotia": "estr_velha_cotia",
    "estr v. itu": "estr_velha_itu",
    "estr v.itu": "estr_velha_itu",
    "estr velha itu": "estr_velha_itu",
    "estr. velha itu": "estr_velha_itu",
    "estr.velha itu": "estr_velha_itu",
    "estr romeiros": "estr_romeiros",
    "etiópia": "etiopia",
    "etiopia": "etiopia",
    "eurip r. pardal": "eurip_r_pardal",
    "eurip r pardal": "eurip_r_pardal",
    "eurofarma": "eurofarma",
    "galeão": "galeao",
    "galeao": "galeao",
    "galpão verde": "galpao_verde",
    "galpao verde": "galpao_verde",
    "garça": "garca",
    "garca": "garca",
    "gupê": "gupe",
    "gupe": "gupe",
    "gupê alberniz": "gupe",
    "gupe alberniz": "gupe",
    "gupê corelli": "gupe",
    "gupe corelli": "gupe",
    "gupê granados": "gupe",
    "gupe granados": "gupe",
    "gupê pania 02": "gupe",
    "gupe pania 02": "gupe",
    "gupê wagner": "gupe",
    "gupe wagner": "gupe",
    "h. gianella": "h_gianella",
    "h.gianella": "h_gianella",
    "hiroshi okada": "hiroshi_okada",
    "howard acheson": "howard_acheson",
    "ibitinga": "ibitinga",
    "iguassu": "iguassu",
    "imirim": "imirim",
    "indonésia": "indonesia",
    "indonesia": "indonesia",
    "indonésia *": "indonesia",
    "indonesia *": "indonesia",
    "ipê": "ipe",
    "ipe": "ipe",
    "itaqueti": "itaqueti",
    "itaqui": "itaqui",
    "iucas": "iucas",
    "jaú": "jau",
    "jau": "jau",
    "jaú mesopotâ": "jau",
    "jau mesopotam": "jau",
    "jau mesopotâ": "jau",
    "jaú/mesopotâ": "jau",
    "jau/mesopotâ": "jau",
    "jau/mesopotam": "jau",
    "jaú *": "jau",
    "jau *": "jau",
    "joão de goes": "joao_de_goes",
    "joao de goes": "joao_de_goes",
    "joão de góes": "joao_de_goes",
    "joao de góes": "joao_de_goes",
    "joão de goes 10": "joao_de_goes",
    "joao de goes 10": "joao_de_goes",
    "joão de góes 10": "joao_de_goes",
    "joao de góes 10": "joao_de_goes",
    "joão de goes 7/8": "joao_de_goes",
    "joao de goes 7/8": "joao_de_goes",
    "joão de góes 7/8": "joao_de_goes",
    "joao de góes 7/8": "joao_de_goes",
    "joão de goes a1": "joao_de_goes",
    "joao de goes a1": "joao_de_goes",
    "joão de góes a1": "joao_de_goes",
    "joao de góes a1": "joao_de_goes",
    "joão de goes a2": "joao_de_goes",
    "joao de goes a2": "joao_de_goes",
    "joão de góes a2": "joao_de_goes",
    "joao de góes a2": "joao_de_goes",
    "joão de goes gb": "joao_de_goes",
    "joao de goes gb": "joao_de_goes",
    "joão de góes gb": "joao_de_goes",
    "joao de góes gb": "joao_de_goes",
    "joão e cortes": "joao_e_cortes",
    "joao e cortes": "joao_e_cortes",
    "joão v l quero": "joao_villalobos_quero",
    "joao v l quero": "joao_villalobos_quero",
    "joão villalobo q": "joao_villalobos_quero",
    "joao villalobo q": "joao_villalobos_quero",
    "joão villalobo": "joao_villalobos_quero",
    "joao villalobo": "joao_villalobos_quero",
    "jvlq": "joao_villalobos_quero",
    "jvlq chopin": "joao_villalobos_quero",
    "jvlq palestrina": "joao_villalobos_quero",
    "villalobo quero": "joao_villalobos_quero",
    "julio mes": "julio_mesquita",
    "julio mesquita": "julio_mesquita",
    "julio ourin": "julio_mesquita",
    "julio mes/ourin": "julio_mesquita",
    "lagoa nova": "lagoa_nova",
    "lapa": "lapa",
    "lourenço zacaro": "lourenco_beloli",
    "lourenco zacaro": "lourenco_beloli",
    "lorenço beloli": "lourenco_beloli",
    "lorenco beloli": "lourenco_beloli",
    "lourenço beloli": "lourenco_beloli",
    "lourenco beloli": "lourenco_beloli",
    "macatuba": "macatuba",
    "mar creta": "mar_creta",
    "mississipe": "mississipe",
    "moacir da silveira": "moacir_da_silveira",
    "monte fuji": "monte_fuji",
    "monte gamele": "monte_gamele",
    "municipios": "municipios",
    "municípios": "municipios",
    "pirituba": "pirituba",
    "plasteng": "plasteng",
    "ponte das pedra": "ponte_das_pedras",
    "ponte das pedras": "ponte_das_pedras",
    "ponte das pedra162": "ponte_das_pedras",
    "porto alegre": "porto_alegre",
    "pureza marques": "pureza_marques",
    "rosa scarpa": "rosa_scarpa",
    "saburo sumya": "saburo_sumya",
    "salete": "salete",
    "samambaias": "samambaias",
    "santa monica": "santa_monica",
    "sta monica cotia": "santa_monica",
    "saracura": "saracura",
    "seikiti nakayam": "seikiti_nakayama",
    "seikiti nakayama": "seikiti_nakayama",
    "sentinelas": "sentinelas",
    "sto antonio": "sto_antonio",
    "sto antônio": "sto_antonio",
    "tatuapé": "tatuape",
    "tatuape": "tatuape",
    "titicaca": "titicaca",
    "trevo jandira": "trevo_jandira",
    "tucanos": "tucanos",
    "udiaço": "udiaco",
    "udiaco": "udiaco",
    "urano": "urano",
    "vernon krielb": "vernon_krieble",
    "vernon krieble": "vernon_krieble",
    "vicente rod silv": "vicente_rod_silva",
    "vicente rod silva": "vicente_rod_silva",
    "vitor a fortunato": "vitor_a_fortunato",
    "waldemar p oli": "waldemar_p_oliveira",
    "waldemar p oliveira": "waldemar_p_oliveira",

    # -- Santana de Parnaíba --
    "alagoas": "alagoas",
    "araco": "araco",
    "avencas": "avencas",
    "cerquilho": "cerquilho",
    "fortaleza": "fortaleza",
    "gabriel salomão": "gabriel_salomao",
    "gabriel salomao": "gabriel_salomao",
    "gilbert carvalho": "gilbert_carvalho",
    "gregorio spina": "gregorio_spina",
    "gregório spina": "gregorio_spina",
    "guanabara": "guanabara",
    "marica marques": "marica_marques",
    "márica marques": "marica_marques",
    "mato grosso": "mato_grosso",
    "natal": "natal",
    "para": "para",
    "pará": "para",
    "paraná": "parana",
    "parana": "parana",
    "pernanbuco": "pernambuco",
    "pernambuco": "pernambuco",
    "rio branco": "rio_branco",
    "rio de janeiro": "rio_de_janeiro",
    "rio de  janeiro": "rio_de_janeiro",
    "sergipe": "sergipe",
    "silvana": "silvana",

    # -- Polo Industrial Jandira --
    "anterina g fº": "anterina_g_fo",
    "anterina g fo": "anterina_g_fo",
    "antero godoy": "antero_godoy",
    "anthero godoy": "antero_godoy",
    "anthero  godoy": "antero_godoy",
    "aparicio godoy": "aparicio_godoy",
    "aparício godoy": "aparicio_godoy",
    "aparicio  godoy": "aparicio_godoy",
    "arthemio dioni": "arthemio_dioni",
    "genésio santos": "genesio_santos",
    "genesio santos": "genesio_santos",
    "giovanni luchini": "giovanni_luchini",
    "giovani luchinni": "giovanni_luchini",
    "gpl itapevi i": "gpl_itapevi_i",
    "gpl itapevi": "gpl_itapevi_i",
    "gpl jand ii": "gpl_jand_ii",
    "j.albino pereira": "j_albino_pereira",
    "j. albino pereira": "j_albino_pereira",
    "j albino pereira": "j_albino_pereira",
    "j.pereira possid": "j_pereira_possid",
    "j. pereira possid": "j_pereira_possid",
    "j pereira possid": "j_pereira_possid",
    "joão d ribeiro": "joao_d_ribeiro",
    "joao d ribeiro": "joao_d_ribeiro",
    "luiza oliveira": "luiza_oliveira",
    "orlando mota": "orlando_mota",

    # -- Various / Rodovias / Other --
    "amélia guimarães": "amelia_guimaraes",
    "amelia guimaraes": "amelia_guimaraes",
    "amélia guimaraes": "amelia_guimaraes",
    "alpha norte": "alpha_norte",
    "cap fco cesar": "cap_fco_cesar",
    "alb jack byingto": "alb_jack_byington",
    "alb jack byington": "alb_jack_byington",
    "anhanguera": "anhanguera",
    "charqueada": "charqueada",
    "jean anastace": "jean_anastace",
    "jean anastácio": "jean_anastace",
    "jose m ribeiro": "jose_m_ribeiro",
    "josé m ribeiro": "jose_m_ribeiro",
    "jurua 314/370": "jurua",
    "marco - chacara": "marco_chacara",
    "marco chacara": "marco_chacara",
    "maranhão": "maranhao",
    "maranhao": "maranhao",
    "marg ribeirão": "marg_ribeirao",
    "marg ribeirao": "marg_ribeirao",
    "miriam": "miriam",
    "morada estrelas": "morada_estrelas",
    "morada das estrelas": "morada_estrelas",
    "paraguaçu": "paraguacu",
    "paraguacu": "paraguacu",
    "paraiso": "paraiso",
    "paraíso": "paraiso",
    "parana ga": "parana",
    "parana gb": "parana",
    "parana gc": "parana",
    "paraná gb": "parana",
    "pinheiros": "pinheiros",
    "portugal": "portugal",
    "portugal 7a": "portugal",
    "portugal 7b": "portugal",
    "portugal 8a": "portugal",
    "rio pardo": "rio_pardo",
    "são j. araguaia": "sao_j_araguaia",
    "sao j. araguaia": "sao_j_araguaia",
    "são j araguaia": "sao_j_araguaia",
    "sao j araguaia": "sao_j_araguaia",
    "trix loja 03": "trix",
    "trix loja": "trix",
    "km 23 castello": "km_castello",
    "km 33.5 castello": "km_castello",
    "km 33,5 castello": "km_castello",
    "km 39 castello": "km_castello",
    "km 53 castello": "km_castello",
    "km 68 castello": "km_castello",
    "km23 castello": "km_castello",
    "km33.5 castello": "km_castello",
    "km39 castello": "km_castello",
    "km53 castello": "km_castello",
    "km68 castello": "km_castello",
    "marg. castello": "marg_castello",
    "marg castello": "marg_castello",
    "melville": "melville",
    "melville m.quit": "melville",
    "n.s. da penha": "ns_da_penha",
    "n.s.da penha": "ns_da_penha",
    "ns da penha": "ns_da_penha",
    "nicolau f souza": "nicolau_f_souza",
    "nova hamburgo": "nova_hamburgo",
    "nova s. paulo": "nova_sao_paulo",
    "nova s.paulo": "nova_sao_paulo",
    "nova são paulo": "nova_sao_paulo",
    "nova sao paulo": "nova_sao_paulo",
    "oscar bressane": "oscar_bressane",
    "ourinhos": "ourinhos",
    "rap tavares": "raposo_tavares",
    "raposo tavares": "raposo_tavares",
    "rodoanel": "rodoanel",
    "romeiros": "romeiros",
    "romeiros 122": "romeiros",
    "romeiros 146": "romeiros",
    "romeiros 165": "romeiros",
    "romeiros 170": "romeiros",
    "romeiros 184": "romeiros",
    "romeiros 220": "romeiros",
    "romeiros 240": "romeiros",
    "romeiros 254": "romeiros",
    "romeiros spar": "romeiros",
    "scala": "scala",
    "fern cer c coim": "fernando_cerqueira",
    "fernan cerquei": "fernando_cerqueira",
    "tenente marques": "tenente_marques",
    "ten marques": "tenente_marques",
    "ten marq": "tenente_marques",
    "ten marq/amaz": "tenente_marques",
    "ten marques/amaz": "tenente_marques",
}

# ---------------------------------------------------------------------------
# STREET_INFO
# ---------------------------------------------------------------------------
# Maps canonical key -> (logradouro_tipo, nome_oficial).

STREET_INFO: dict[str, tuple[str, str]] = {
    # -- Alphaville Industrial (Alameda) --
    "africa": ("Alameda", "África"),
    "aldeinha": ("Alameda", "Aldeinha"),
    "amazonas": ("Alameda", "Amazonas"),
    "amazonas_fazendinha": ("Rua", "Amazonas"),
    "america": ("Alameda", "América"),
    "araguacema": ("Alameda", "Araguacema"),
    "araguaia": ("Alameda", "Araguaia"),
    "arapoema": ("Alameda", "Arapoema"),
    "aruanã": ("Alameda", "Aruanã"),
    "asia": ("Alameda", "Ásia"),
    "bahia": ("Alameda", "Bahia"),
    "caiapos": ("Alameda", "Caiapós"),
    "ceara": ("Alameda", "Ceará"),
    "ceci": ("Alameda", "Ceci"),
    "dib_sauaia": ("Alameda", "Dib Sauaia"),
    "europa": ("Alameda", "Europa"),
    "grajau": ("Alameda", "Grajaú"),
    "hon_alv_pente": ("Alameda", "Honorato Álvares Penteado"),
    "ibateguara": ("Alameda", "Ibateguara"),
    "inaja": ("Alameda", "Inajá"),
    "javari": ("Alameda", "Javari"),
    "joao_f_camargo": ("Alameda", "João Fernandes de Camargo"),
    "jose_pereira_sb": ("Alameda", "José Pereira Sb"),
    "juari": ("Alameda", "Juari"),
    "jurua": ("Alameda", "Juruá"),
    "jussara": ("Alameda", "Jussara"),
    "madeira": ("Alameda", "Madeira"),
    "marg_projetada": ("Alameda", "Marginal Projetada"),
    "modular_i": ("Condomínio", "Modular I"),
    "modular_ii": ("Condomínio", "Modular II"),
    "oceania": ("Alameda", "Oceania"),
    "piracema": ("Alameda", "Piracema"),
    "piraiba": ("Alameda", "Piraíba"),
    "piramboia": ("Alameda", "Pirambóia"),
    "pucurui": ("Alameda", "Pucuruí"),
    "rio_negro": ("Alameda", "Rio Negro"),
    "rio_preto": ("Alameda", "Rio Preto"),
    "sao_paulo": ("Alameda", "São Paulo"),
    "surubiju": ("Alameda", "Surubiju"),
    "tambaqui": ("Alameda", "Tambaqui"),
    "tambore": ("Alameda", "Tamboré"),
    "tocantins": ("Alameda", "Tocantins"),
    "trevo_alphaville": ("Alameda", "Trevo de Alphaville"),
    "trix": ("Condomínio", "TRIX"),
    "tucunare": ("Alameda", "Tucunaré"),
    "victorino_calegare": ("Alameda", "Victorino Calegare"),
    "xingu": ("Alameda", "Xingu"),
    "yojiro_takaoka": ("Avenida", "Yojiro Takaoka"),
    "marcos_ulhoa": ("Avenida", "Marcos Penteado de Ulhôa Rodrigues"),

    # -- Estradas --
    "estr_mun_boa_vista": ("Estrada", "Municipal Boa Vista"),
    "estr_alpes_beriolo": ("Estrada", "dos Alpes de Bériolo"),
    "estr_da_balsa": ("Estrada", "da Balsa"),
    "estr_da_cachoeira": ("Estrada", "da Cachoeira"),
    "estr_do_ingai": ("Estrada", "do Ingaí"),
    "estr_do_itaqui": ("Estrada", "do Itaqui"),
    "estr_do_zilo": ("Estrada", "do Zilo"),
    "estr_emilio_scaff": ("Estrada", "Emílio Scaff"),
    "estr_nacoes": ("Estrada", "das Nações"),
    "estr_velha_cotia": ("Estrada", "Velha de Cotia"),
    "estr_velha_itu": ("Estrada", "Velha de Itu"),
    "estr_romeiros": ("Estrada", "dos Romeiros"),
    "romeiros": ("Estrada", "dos Romeiros"),

    # -- Rodovias --
    "km_castello": ("Rodovia", "Presidente Castelo Branco"),
    "marg_castello": ("Marginal", "Rodovia Presidente Castelo Branco"),
    "raposo_tavares": ("Rodovia", "Raposo Tavares"),
    "rodoanel": ("Rodovia", "Rodoanel Mário Covas"),

    # -- Barueri --
    "abaetetuba": ("Rua", "Abaetetuba"),
    "abelardo_luz": ("Rua", "Abelardo Luz"),
    "aeroporto": ("Rua", "Aeroporto"),
    "alfredo_bicasa": ("Rua", "Alfredo Bicasa"),
    "amor_perfeito": ("Rua", "Amor Perfeito"),
    "antilhas": ("Rua", "Antilhas"),
    "anton_saviano": ("Rua", "Anton Saviano"),
    "aquario": ("Rua", "Aquário"),
    "araras": ("Rua", "Araras"),
    "atenas": ("Rua", "Atenas"),
    "av_marco": ("Avenida", "Marco"),
    "barueri_mirim": ("Rua", "Barueri Mirim"),
    "benedito_turibio": ("Rua", "Benedito Antônio Turíbio"),
    "betha_trindade": ("Rua", "Betha Trindade"),
    "bethaville": ("Rua", "Bethaville"),
    "bica": ("Rua", "Bica"),
    "boa_vista": ("Rua", "Boa Vista"),
    "brasil": ("Rua", "Brasil"),
    "brasilandia": ("Rua", "Brasilândia"),
    "brooklin": ("Rua", "Brooklin"),
    "ce_itaqui": ("Condomínio", "Centro Empresarial Itaqui"),
    "cl_itapevi": ("Condomínio", "Centro Logístico Itapevi"),
    "cachoeira": ("Rua", "Cachoeira"),
    "calil_mohamed": ("Rua", "Calil Mohamed"),
    "campo_grande": ("Rua", "Campo Grande"),
    "capitais": ("Rua", "Capitais"),
    "castelo_branco": ("Rua", "Castelo Branco"),
    "chaves": ("Rua", "Chaves"),
    "cicero_b_morais": ("Rua", "Cícero B. Morais"),
    "constantinopla": ("Rua", "Constantinopla"),
    "dario_almonacid": ("Rua", "Dário Almonacid"),
    "emilio_b_silva": ("Rua", "Emílio B. Silva"),
    "espirito_santo": ("Rua", "Espírito Santo"),
    "estados": ("Rua", "Estados"),
    "etiopia": ("Rua", "Etiópia"),
    "eurip_r_pardal": ("Rua", "Eurípides R. Pardal"),
    "eurofarma": ("Rua", "Eurofarma"),
    "galeao": ("Rua", "Galeão"),
    "galpao_verde": ("Condomínio", "Galpão Verde"),
    "garca": ("Rua", "Garça"),
    "gupe": ("Rua", "Gupê"),
    "h_gianella": ("Rua", "H. Gianella"),
    "hiroshi_okada": ("Rua", "Hiroshi Okada"),
    "howard_acheson": ("Rua", "Howard Acheson"),
    "ibitinga": ("Rua", "Ibitinga"),
    "iguassu": ("Rua", "Iguassu"),
    "imirim": ("Rua", "Imirim"),
    "indonesia": ("Rua", "Indonésia"),
    "ipe": ("Rua", "Ipê"),
    "itaqueti": ("Rua", "Itaqueti"),
    "itaqui": ("Rua", "Itaqui"),
    "iucas": ("Rua", "Iucas"),
    "jau": ("Rua", "Jaú"),
    "joao_de_goes": ("Rua", "João de Góes"),
    "joao_e_cortes": ("Rua", "João E. Cortes"),
    "joao_villalobos_quero": ("Rua", "João Villalobos Quero"),
    "julio_mesquita": ("Rua", "Júlio Mesquita"),
    "lagoa_nova": ("Rua", "Lagoa Nova"),
    "lapa": ("Rua", "Lapa"),
    "lourenco_beloli": ("Rua", "Lourenço Beloli"),
    "macatuba": ("Rua", "Macatuba"),
    "mar_creta": ("Rua", "Mar Creta"),
    "mississipe": ("Rua", "Mississipe"),
    "moacir_da_silveira": ("Rua", "Moacir da Silveira"),
    "monte_fuji": ("Rua", "Monte Fuji"),
    "monte_gamele": ("Rua", "Monte Gamele"),
    "municipios": ("Rua", "Municípios"),
    "pirituba": ("Rua", "Pirituba"),
    "plasteng": ("Condomínio", "Plasteng"),
    "ponte_das_pedras": ("Rua", "Ponte das Pedras"),
    "porto_alegre": ("Rua", "Porto Alegre"),
    "pureza_marques": ("Rua", "Pureza Marques"),
    "rosa_scarpa": ("Rua", "Rosa Scarpa"),
    "saburo_sumya": ("Rua", "Saburo Sumya"),
    "salete": ("Rua", "Salete"),
    "samambaias": ("Rua", "Samambaias"),
    "santa_monica": ("Rua", "Santa Mônica"),
    "saracura": ("Rua", "Saracura"),
    "seikiti_nakayama": ("Rua", "Seikiti Nakayama"),
    "sentinelas": ("Rua", "Sentinelas"),
    "sto_antonio": ("Rua", "Santo Antônio"),
    "tatuape": ("Rua", "Tatuapé"),
    "titicaca": ("Rua", "Titicaca"),
    "trevo_jandira": ("Rua", "Trevo Jandira"),
    "tucanos": ("Rua", "Tucanos"),
    "udiaco": ("Rua", "UDIAÇO"),
    "urano": ("Rua", "Urano"),
    "vernon_krieble": ("Rua", "Vernon Krieble"),
    "vicente_rod_silva": ("Rua", "Vicente Rodrigues da Silva"),
    "vitor_a_fortunato": ("Rua", "Vitor A. Fortunato"),
    "waldemar_p_oliveira": ("Rua", "Waldemar P. Oliveira"),

    # -- Santana de Parnaíba --
    "alagoas": ("Rua", "Alagoas"),
    "araco": ("Rua", "Araco"),
    "avencas": ("Rua", "Avencas"),
    "cerquilho": ("Rua", "Cerquilho"),
    "fortaleza": ("Rua", "Fortaleza"),
    "gabriel_salomao": ("Rua", "Gabriel Salomão"),
    "gilbert_carvalho": ("Rua", "Gilbert Carvalho"),
    "gregorio_spina": ("Rua", "Gregório Spina"),
    "guanabara": ("Rua", "Guanabara"),
    "marica_marques": ("Rua", "Márica Marques"),
    "mato_grosso": ("Rua", "Mato Grosso"),
    "natal": ("Rua", "Natal"),
    "para": ("Rua", "Pará"),
    "parana": ("Rua", "Paraná"),
    "pernambuco": ("Rua", "Pernambuco"),
    "rio_branco": ("Rua", "Rio Branco"),
    "rio_de_janeiro": ("Rua", "Rio de Janeiro"),
    "sergipe": ("Rua", "Sergipe"),
    "silvana": ("Rua", "Silvana"),

    # -- Polo Industrial Jandira --
    "anterina_g_fo": ("Rua", "Anterina G. Filho"),
    "antero_godoy": ("Rua", "Antero Godoy"),
    "aparicio_godoy": ("Rua", "Aparício Godoy"),
    "arthemio_dioni": ("Rua", "Arthêmio Dioni"),
    "genesio_santos": ("Rua", "Genésio Santos"),
    "giovanni_luchini": ("Rua", "Giovanni Luchini"),
    "gpl_itapevi_i": ("Condomínio", "GPL Itapevi I"),
    "gpl_jand_ii": ("Condomínio", "GPL Jandira II"),
    "j_albino_pereira": ("Rua", "J. Albino Pereira"),
    "j_pereira_possid": ("Rua", "J. Pereira Possidônio"),
    "joao_d_ribeiro": ("Rua", "João D. Ribeiro"),
    "luiza_oliveira": ("Rua", "Luiza Oliveira"),
    "orlando_mota": ("Rua", "Orlando Mota"),

    # -- Various / Other --
    "amelia_guimaraes": ("Rua", "Amélia Guimarães"),
    "alpha_norte": ("Avenida", "Alpha Norte"),
    "cap_fco_cesar": ("Rua", "Capitão Francisco César"),
    "melville": ("Rua", "Melville"),
    "ns_da_penha": ("Rua", "Nossa Senhora da Penha"),
    "nicolau_f_souza": ("Rua", "Nicolau F. Souza"),
    "nova_hamburgo": ("Rua", "Nova Hamburgo"),
    "nova_sao_paulo": ("Rua", "Nova São Paulo"),
    "oscar_bressane": ("Rua", "Oscar Bressane"),
    "ourinhos": ("Rua", "Ourinhos"),
    "scala": ("Condomínio", "Scala"),
    "fernando_cerqueira": ("Rua", "Fernando Cerqueira Coimbra"),
    "tenente_marques": ("Estrada", "Tenente Marques"),
    "alb_jack_byington": ("Rua", "Alberto Jack Byington"),
    "anhanguera": ("Avenida", "Anhanguera"),
    "charqueada": ("Rua", "Charqueada"),
    "jean_anastace": ("Rua", "Jean Anastácio"),
    "jose_m_ribeiro": ("Rua", "José M. Ribeiro"),
    "marco_chacara": ("Rua", "Marco (Chácara)"),
    "maranhao": ("Rua", "Maranhão"),
    "marg_ribeirao": ("Marginal", "Ribeirão"),
    "miriam": ("Rua", "Miriam"),
    "morada_estrelas": ("Rua", "Morada das Estrelas"),
    "paraguacu": ("Rua", "Paraguaçu"),
    "paraiso": ("Rua", "Paraíso"),
    "pinheiros": ("Rua", "Pinheiros"),
    "portugal": ("Rua", "Portugal"),
    "rio_pardo": ("Rua", "Rio Pardo"),
    "sao_j_araguaia": ("Rua", "São José do Araguaia"),
}
